[agents]
max_threads = 20
max_depth = 3

[apps.asdk_app_69a1d78e929881919bba0dbda1f6436d]
enabled = false

[tool_suggest]
disabled_tools = [
  { type = "plugin", id = "slack@openai-curated-remote" },
  { type = "plugin", id = "slack@openai-curated" },
]
